# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93dbd7e5e89dc13b7ea5ae30eae55650afa82b5a12a9c8f2dd5256bf68167aedd005be5b4ff096f08614c4d98a4c81bcbbf98cd4e3bffb40f084e67d8546aa4c

test:
  secret_key_base: ea953e188cbbd96fae5c136a80153b9ea5d61ce269bd1cad3fbcfa611589d04a46d9d88bff59f5bd47925bc9f1d016d3d5fff4cfc7e9143b0c6c53c13773dc34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
